### ISSUE TITLE
Inference time

### ISSUE THREAD

**Issue by SuHoHan95** [hustvl/CrossVIS#6]
Thank you for the great project!!
I try to test your project using provided checkpoints.
However, I get the inference speed of 25.6, 23.3. 
These speeds are slower than reported in the paper with a  large margin.
May I know why there is such a difference?

Here is my environment: i9-9960X CPU, 2080ti GPU

**Comment by vealocia** [comment]
I guess the main cause lays in whether the time costs of data loading and tracking are involved.
Both time costs are ignored when we measure the inference speed because we believe both data loading and tracking are method- and hardware- aware.
Lots of efforts could be done to further boost the two processes under certain application demands.
Thanks for your interests in our work!

**Comment by fxooooooooo** [comment]
> 谢谢你的伟大项目！！ 我尝试使用提供的检查点测试您的项目。 但是，我得到 25.6、23.3 的推理速度。 这些速度比论文中报告的速度要慢很多。 我可以知道为什么会有这样的差异吗？
> 
> 这是我的环境：i9-9960X CPU，2080ti GPU

Hello, how to calculate such an  25.6、23.3 inference speed value? [01:01<00:00, 1.16s/it] when I run test_vis.py
